server:
  address: "0.0.0.0"
  port: "${PORT:8080}"

spring:
  application:
    name: "xoxo-pos-backend"

  datasource:
    url: "${DATABASE_URL}"
    username: "${POSTGRES_USER}
    password: "${POSTGRES_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

app:
  jwt:
    secret: "${JWT_SECRET:xoxo-pos-cambiar-esta-clave-en-railway-12345678901234567890}"
    expiration-minutes: 720

  cors:
    allowed-origin: "${FRONTEND_URL:http://localhost:5173}"

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
